spring.application.name=java-devops-e2e-app
server.port=8080

# Logging
logging.level.root=INFO

# Actuator (health checks)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

